### ISSUE TITLE
Comment 관련 Component 성능 개선 및 기능 추가

### ISSUE THREAD

**Issue by SeongYeongJu** [ehfdl/celebfive#43]
- 사용자 설문 테스트 후 댓글 입력 시 테스트 결과에 맞는 별명(Nick Name)이 생기도록 변경.
- 별명 데이터가 Firebase로부터 GET이 제대로 되지 않아 null로 나타나는 현상 해결.
- 댓글을 수정, 삭제할 때 해당 댓글을 작성한 사용자만 수정, 삭제 기능을 사용할 수 있도록 변경.

**Comment by Hah-nna** [comment]
우리조 GOSU... 프젝란에 DONE으로 가게끔 해놨습니다
